const translations = {
		en: {
			player: "Daniel Atienza",
			main_title: "Daniel Atienza",
			role: "Software Developer & CTO",
			quest_log: "NAVIGATION",
			quest_1: "About",
			quest_2: "Skills",
			quest_3: "Portfolio",
			about_title: "About Me",
			about_p1: "I am a Computer Engineer with a strong passion for emerging technologies and continuous learning.",
			about_p2: "Currently, I work as CTO and Lead Programmer, driving strategic decision-making and fostering a healthy, productive team environment.",
			about_p3: "My experience covers development with Unity, Photon, and Virtual Reality projects.",
			skills_title: "Core Technologies",
			skill_english: "English B2",
			portfolio_title: "Experience & Projects",
			btn_all: "All",
			btn_exp: "Experience",
			btn_proj: "Projects",
			btn_edu: "Education",
			date_present: "Oct 2024 - Present",
			job_cto: "CTO & Lead Programmer",
			proj_vr_rev: "Virtual Revolution Project",
			btn_details: "More details",
			proj_personal: "Personal Project",
			btn_google: "View on Google Play",
			date_uni: "2020 - 2024",
			edu_uni: "University of Almería",
			edu_degree: "Computer Engineering Degree",
			date_verajoker: "Apr 2019 - Sep 2019",
			job_tech: "IT Technician",
			date_esistemas: "Mar 2018 - Jun 2018",
			btn_youtube: "Watch on YouTube",
			edu_asir: "Network Computer Systems Administration",
			date_computerstore: "Mar 2015 - Jun 2015",
			edu_smr: "Microcomputer Systems and Networks",
			ach_start: "Welcome to my portfolio!",
			ach_mid: "Exploring the projects...",
			ach_end: "Thanks for scrolling!",
			ach_unlocked: ""
		},
		es: {
			player: "Daniel Atienza",
			main_title: "Daniel Atienza",
			role: "Desarrollador de Software y CTO",
			quest_log: "NAVEGACIÓN",
			quest_1: "Sobre mí",
			quest_2: "Habilidades",
			quest_3: "Portafolio",
			about_title: "Sobre Mí",
			about_p1: "Soy Ingeniero Informático, un apasionado de las nuevas tecnologías y del aprendizaje continuo.",
			about_p2: "Actualmente, me desempeño como CTO y Lead Programmer, liderando la toma de decisiones estratégicas y promoviendo un entorno de trabajo saludable y productivo.",
			about_p3: "Mi experiencia abarca el desarrollo con Unity, Photon y proyectos en Realidad Virtual.",
			skills_title: "Tecnologías Principales",
			skill_english: "Inglés B2",
			portfolio_title: "Experiencia y Proyectos",
			btn_all: "Todo",
			btn_exp: "Experiencia",
			btn_proj: "Proyectos",
			btn_edu: "Formación",
			date_present: "Oct 2024 - Presente",
			job_cto: "CTO y Lead de Programación",
			proj_vr_rev: "Proyecto de Virtual Revolution",
			btn_details: "Más detalles",
			proj_personal: "Proyecto Personal",
			btn_google: "Ver en Google Play",
			date_uni: "2020 - 2024",
			edu_uni: "Universidad de Almería",
			edu_degree: "Grado en Ingeniería Informática",
			date_verajoker: "Abr 2019 - Sep 2019",
			job_tech: "Técnico Informático",
			date_esistemas: "Mar 2018 - Jun 2018",
			btn_youtube: "Ver en YouTube",
			edu_asir: "Administración de Sistemas Informáticos en Red",
			date_computerstore: "Mar 2015 - Jun 2015",
			edu_smr: "Sistemas Microinformáticos y Redes",
			ach_start: "¡Bienvenido a mi portafolio!",
			ach_mid: "Explorando los proyectos...",
			ach_end: "¡Gracias por llegar hasta aquí!",
			ach_unlocked: ""
		}
	};